name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:



jobs:

  build:

    runs-on: ubuntu-22.04
    
    container:
      image: debian:11
      
    steps:
    - uses: actions/checkout@v4
    - name: Install build tools
      run: |
        apt-get update -y
        apt-get install -y make gcc g++   # или build-essential, если нужен полный набор
    - name: make
      run: |
        make clean || true
        CXXFLAGS="-D_GLIBCXX_USE_CXX11_ABI=0 -O2" make
    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
        name: libhook-proto
        path: |
          **/*.so
        if-no-files-found: error
